#!/bin/bash

# ONEPA Playout PRO - Enhanced Universal Installer (Linux/macOS)
# Features:
# - Auto-detects Docker
# - Generates secure .env file
# - Checks ports
# - Sets up directories
# - Launches system

set -e

# Colors
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m' # No Color

echo -e "${GREEN}🚀 ONEPA Playout PRO - Total Automation Installer${NC}"
echo "--------------------------------------------------"

# 1. Helper Functions
check_command() {
    if ! command -v "$1" &> /dev/null; then
        echo -e "${RED}❌ $1 não encontrado.${NC}"
        return 1
    fi
    return 0
}

check_port() {
    local port=$1
    if lsof -Pi :$port -sTCP:LISTEN -t >/dev/null ; then
        echo -e "${YELLOW}⚠️  Porta $port parece estar em uso. Isto pode causar conflitos.${NC}"
    fi
}

generate_password() {
    openssl rand -hex 16
}

# 2. Pre-flight Checks
echo "🔍 Verificando requisitos..."

if ! check_command "docker"; then
    echo "➡️  Por favor, instale o Docker: https://docs.docker.com/get-docker/"
    exit 1
fi

if ! docker compose version &> /dev/null; then
    echo -e "${YELLOW}⚠️  'docker compose' V2 não detetado. Tentando 'docker-compose' V1...${NC}"
    if ! check_command "docker-compose"; then
        echo -e "${RED}❌ Nenhum Docker Compose encontrado.${NC}"
        exit 1
    fi
    DOCKER_COMPOSE="docker-compose"
else
    DOCKER_COMPOSE="docker compose"
fi

echo "✅ Docker ambiente: OK"

# 3. Port Check
check_port 3000
check_port 8081
check_port 1935

# 4. Environment Setup
if [ ! -f .env ]; then
    echo "⚙️  Configurando ambiente (.env)..."
    cat <<EOF > .env
# Auto-generated by install.sh
POSTGRES_USER=onepa
POSTGRES_PASSWORD=$(generate_password)
POSTGRES_DB=onepa_playout
JWT_SECRET=$(generate_password)
MEDIA_PATH=/var/lib/onepa-playout/media
THUMBNAILS_PATH=/var/lib/onepa-playout/thumbnails
# Optional: External APIs (Fill manually via Settings later)
TMDB_API_KEY=
OMDB_API_KEY=
EOF
    echo -e "${GREEN}✅ Arquivo .env gerado com senhas seguras.${NC}"
else
    echo "✅ Arquivo .env já existe. Mantendo."
fi

# 5. Directories
echo "📁 Preparando sistema de arquivos..."
mkdir -p data/postgres data/media data/thumbnails data/playlists data/assets/protected
chmod -R 777 data/media data/thumbnails data/playlists 2>/dev/null || true

# 6. Launch
echo "🏗️  Construindo e iniciando contentores... (Aguarde)"
$DOCKER_COMPOSE down --remove-orphans 2>/dev/null || true
$DOCKER_COMPOSE build --pull
$DOCKER_COMPOSE up -d

echo ""
echo -e "${GREEN}✅ Instalação Concluída com Sucesso!${NC}"
echo "--------------------------------------------------"
echo -e "🌐 Frontend: ${GREEN}http://localhost:3000${NC}"
echo -e "🔧 Backend:  http://localhost:8081"
echo -e "📡 Stream:   http://localhost:3000/hls/stream.m3u8"
echo "--------------------------------------------------"
echo "🔑 Login padrão: admin / admin"
echo "⚠️  Nota: Altere a senha após o primeiro login."
echo ""
