#!/bin/bash

# ONEPA Playout PRO - Enhanced Universal Installer (Linux/macOS)
# Version: 2.2.0-ALPHA.5-PRO
# Features: GitHub Cloud Sync, Docker Automation, Source Cleanup

set -e

# --- Configuration & Logging ---
LOG_FILE="install.log"
exec > >(tee -a "$LOG_FILE") 2>&1

GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m'

echo -e "${GREEN}🚀 ONEPA Playout PRO - Total Automation Installer${NC}"
echo "--------------------------------------------------"
echo "Log file: $LOG_FILE"
echo "Date: $(date)"

# --- 1. GitHub Credentials ---
echo -e "\n${YELLOW}🔑 Configuração do GitHub Cloud${NC}"
read -p "GitHub Private Access Token (PAT): " GH_PAT
read -p "Repositório (ex: user/repo) [ENTER p/ padrão]: " GH_REPO
GH_REPO=${GH_REPO:-"ideiasestrondosas-ctrl/cloud-onepa-playout"}
read -p "Branch para Deploy (main, alpha, stable) [ENTER p/ alpha]: " GH_BRANCH
GH_BRANCH=${GH_BRANCH:-"alpha"}

# --- 2. Clone Repository ---
TEMP_DIR="onepa_install_$(date +%s)"
echo -e "\n${YELLOW}⬇️ Clonando repositório ($GH_BRANCH)...${NC}"

if ! git clone -b "$GH_BRANCH" "https://$GH_PAT@github.com/$GH_REPO.git" "$TEMP_DIR"; then
    echo -e "${RED}❌ Falha ao clonar o repositório. Verifique o seu TOKEN e Branch.${NC}"
    exit 1
fi

cd "$TEMP_DIR"

# --- 3. Pre-flight Checks ---
echo -e "\n${YELLOW}🔍 Verificando requisitos...${NC}"

if ! command -v docker &> /dev/null; then
    echo -e "${RED}❌ Docker não encontrado. Por favor, instale o Docker Desktop.${NC}"
    exit 1
fi

DOCKER_COMPOSE="docker compose"
if ! $DOCKER_COMPOSE version &> /dev/null; then
    DOCKER_COMPOSE="docker-compose"
fi

# --- 4. Environment Setup ---
echo -e "\n${YELLOW}⚙️ Configurando variáveis de ambiente...${NC}"
if [ ! -f .env ]; then
    cat <<EOF > .env
# Auto-generated by install.sh
POSTGRES_USER=onepa
POSTGRES_PASSWORD=$(openssl rand -hex 16)
POSTGRES_DB=onepa_playout
JWT_SECRET=$(openssl rand -hex 16)
MEDIA_PATH=/var/lib/onepa-playout/media
THUMBNAILS_PATH=/var/lib/onepa-playout/thumbnails
# Deployment Info
DEPLOY_BRANCH=$GH_BRANCH
DEPLOY_REPO=$GH_REPO
EOF
    echo -e "${GREEN}✅ Arquivo .env gerado.${NC}"
fi

# --- 5. Launch Docker ---
echo -e "\n${YELLOW}🏗️ Preparando Contentores Docker... (Pode demorar)${NC}"
$DOCKER_COMPOSE down --remove-orphans 2>/dev/null || true
$DOCKER_COMPOSE build --pull
$DOCKER_COMPOSE up -d

# --- 6. Cleanup Source Code ---
echo -e "\n${YELLOW}🧹 Limpando código-fonte (Segurança)...${NC}"
# We keep the docker-compose.yml and .env, but remove the src directories
# Move necessary files to parent
mv docker-compose.yml ../
mv .env ../
mv scripts ../
cd ..
rm -rf "$TEMP_DIR"

echo -e "\n${GREEN}✅ Instalação Concluída com Sucesso!${NC}"
echo "--------------------------------------------------"
echo -e "🌐 URL:       ${GREEN}http://localhost:3011${NC}"
echo -e "🔑 Login:      admin / admin"
echo -e "📂 Log:        $LOG_FILE"
echo "--------------------------------------------------"
echo "Para atualizar futuramente, use: ./scripts/update.sh"
echo ""
